database:
  address: "10.250.9.10"
  schema: "config_test_service"
  database: "dev"
  port: "5432"
  username: "dev"
  password: "5FvDf67Lv275sqhKsAKfHitR"
  createSchema: true

moduleName: "config"
grpcOuterAddress:
  ip: 127.0.0.1
  port: 9002

ws:
  rest:
    port: "9011"
    ip: "127.0.0.1"
  grpc:
    port: "9022"
    ip: "127.0.0.1"
  raft:
    port: "9002"
    ip: "0.0.0.0"

metrics:
  gc: true
  memory: true
  address:
    addressConfiguration:
      ip: "0.0.0.0"
      port: "9551"
    path: "/metrics"

cluster:
  dataDir: ./data
  inMemory: true
  outerAddress: 127.0.0.1:9002
  peers:
    - 127.0.0.1:9002
    - 127.0.0.1:9003
    - 127.0.0.1:9004
#    - 127.0.0.1:9006
#    - 127.0.0.1:9001