moduleName: config
instanceUuid: bf482806-0c3d-4e0d-b9d4-12c037b12d70

registry:
  host: nexus.msp.mobi
  username: mp3deployer
  password: ScjKLQuvqfAXu2bs8ysLAvRt

images:
  module: nexus.msp.mobi/msp2/dev/isp-config-service:latest
